image: node:8.9

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - test

test:
  stage: test
  before_script:
    - yarn install
  script:
    - make run-coverage
  artifacts:
    paths:
      - coverage
  only:
    - master

test-lint:
  stage: test
  before_script:
    - yarn install
  script:
    - make test-lint
  only:
    - master